# Generated by Django 5.2.7 on 2025-10-21 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_food_dailymenu_usermealselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermealselection',
            options={'verbose_name': 'انتخاب غذای کاربر', 'verbose_name_plural': 'انتخاب\u200cهای غذا'},
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات غذا'),
        ),
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='عکس غذا'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(unique=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='foods',
            field=models.ManyToManyField(related_name='menus', to='dashboard.food', verbose_name='غذاهای این روز'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام غذا'),
        ),
        migrations.AlterField(
            model_name='usermealselection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='usermealselection',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dailymenu', verbose_name='منو'),
        ),
        migrations.AlterField(
            model_name='usermealselection',
            name='selected_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.food', verbose_name='غذای انتخاب\u200cشده'),
        ),
        migrations.AlterField(
            model_name='usermealselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
