# Generated by Django 5.2.7 on 2025-10-21 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_usermealselection_options_food_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermealselection',
            options={'verbose_name': 'Meal Selection', 'verbose_name_plural': 'Meal Selections'},
        ),
        migrations.AlterField(
            model_name='usermealselection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='usermealselection',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dailymenu', verbose_name='Daily Menu'),
        ),
        migrations.AlterField(
            model_name='usermealselection',
            name='selected_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.food', verbose_name='Selected Food'),
        ),
        migrations.AlterField(
            model_name='usermealselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
