# Generated by Django 5.2.7 on 2025-11-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='dashboard.food'),
        ),
    ]
