# Generated by Django 5.2.7 on 2026-02-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_feedback_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='دلیل غیرفعال بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
