# Generated by Django 5.2.7 on 2026-02-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_organization_dailymenu_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'verbose_name': 'منوی روزانه', 'verbose_name_plural': 'منوهای روزانه'},
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
    ]
